

## This is a function that identifies the hospital with the 
## lowest mortality rate in a given state (1st argument) for a given outcome/cause (2nd argument)

best <- function(state, outcome) {
  
  ## Read outcome data
  data <- read.csv("/Users/Grejell/Desktop/R/Coursera/rprog%2Fdata%2FProgAssignment3-data/outcome-of-care-measures.csv", colClasses = "character")
  
  ## rename the outcome columns
  cause_data <- list("heart attack", "heart failure", "pneumonia")
  names(data)[c(11,17,23)] <- cause_data
  
  ## Check that state and outcome are valid
  
  if((state %in% data$State) == FALSE) stop("invalid state")
  if((outcome %in% cause_data) == FALSE) stop("invalid outcome")
  
  ## Return hospital name in that state with lowest 30-day death
  
  state_data <- data[data$State == state, c("Hospital.Name", outcome)]  ## creates a data.frame that includes only the hospital names
                                                                        ## and specific outcome for the given state
  
  state_data <- state_data[ state_data[, 2] != "Not Available",]
  
  options(warn = -1) ## to ignore the warning message generated by the coercion of NAs in the next line (below)
  
  state_data[, outcome] <- as.numeric(state_data[, outcome]) ## change the data type of the outcome to numeric
  
  state_data <- state_data[order(state_data[, 1]), ]
  
  ## this returns the hospital name which has the best mortality for the given outcome
  
  state_data[which.min(state_data[, 2]), "Hospital.Name"]
}