

## This is a function that ranks (3rd argument) the hospitals from the 
## lowest mortality rate in a given state (1st argument) for a given outcome/cause (2nd argument)


rankhospital <- function(state, outcome, num) {
  
  
  ## Read outcome data
  data <- read.csv("/Users/Grejell/Desktop/R/Coursera/rprog%2Fdata%2FProgAssignment3-data/outcome-of-care-measures.csv", colClasses = "character")
  
  ## rename the outcome columns
  cause_data <- list("heart attack", "heart failure", "pneumonia")
  names(data)[c(11,17,23)] <- cause_data
  
  ## Check that state and outcome are valid
  
  if((state %in% data$State) == FALSE) stop("invalid state")
  if((outcome %in% cause_data) == FALSE) stop("invalid outcome")
  
  ## Return hospital name in that state with lowest 30-day death
  
  state_data <- data[data$State == state, c("Hospital.Name", outcome)]  ## creates a data.frame that includes only the hospital names
  ## and specific outcome for the given state
  
  names(state_data)[2] <- "Rate"
  
  state_data <- state_data[ state_data$Rate != "Not Available",]
  
  options(warn = -1) ## to ignore the warning message generated by the coercion of NAs in the next line (below)
  
  state_data[, 2] <- as.numeric(state_data[, 2]) ## change the data type of the outcome to numeric
  
  state_data <- state_data[order(state_data$Hospital.Name), ]
  
  state_data$Rank <- rank(state_data[, 2], ties.method = "first") ## create a column for outcome rank
  
  state_data <- state_data[order(state_data$Rank), ] ## order the rank
  
  
  ## setting conditions for "best" and "worst" ranked outcome
  
  if (num == "best") {
    num <- 1
  }
  
  if (num == "worst") {
    num <- nrow(state_data)
  }
  
  ## this returns the hospital name of the specified "rank"
  
  if (nrow(state_data) < num) {
    return (NA)
  } else {
  state_data[state_data$Rank == num, 1]
  }
}