

## This is a function that returns the hospital names from each state.
## The returned list are the hospitals that has the ranking (specified in the given rank(2nd argument))
## of the given outcome (1st argument).


rankall <- function(outcome, num) {
  
  ## Read outcome data
  data <- read.csv("/Users/Grejell/Desktop/R/Coursera/rprog%2Fdata%2FProgAssignment3-data/outcome-of-care-measures.csv", colClasses = "character")
  
  ## rename the outcome columns
  cause_data <- list("heart attack", "heart failure", "pneumonia")
  names(data)[c(11,17,23)] <- cause_data
  
  ## Check that state and outcome are valid
  
  if((outcome %in% cause_data) == FALSE) stop("invalid outcome")
  
  ## Return hospital name in that state with lowest 30-day death
  
  state_data <- data[, c("Hospital.Name", outcome, "State")]  ## creates a data.frame that includes only the hospital names
  ## and specific outcome for the given state
  
  names(state_data)[2] <- "Rate"
  
  
  ## run a loop that identifies the result for each State
  
  state_list <- unique(state_data$State)
  
  hospital_result <- character()
  state_result <- character()
  
  for (i in state_list) {
  
    state_data <- state_data[state_data$State == i,]
    
    state_data <- state_data[state_data$Rate != "Not Available",]
  
    options(warn = -1) ## to ignore the warning message generated by the coercion of NAs in the next line (below)
  
    state_data$Rate <- as.numeric(state_data$Rate) ## change the data type of the outcome to numeric

  
    state_data$Rank <- rank(state_data[, 2], ties.method = "first")
  
    state_data <- state_data[order(state_data$Rank), ] ## order the rank
  
  
  ## setting conditions for "best" and "worst" ranked outcome
  
    if (num == "best") {
      num <- 1
    }
  
    if (num == "worst") {
      num <- nrow(state_data)
    }
  
  ## this returns the hospital name of the specified "rank"
  
    if (nrow(state_data) < num) {
      result <- return (NA)
    } else {
      result <- state_data[state_data$Rank == num, c(1,3)]
    }
  
  hospital_result <- c(hospital_result, result)
  state_result <- c(state_result, i)

  }
  
  ranked_list <- cbind(hospital_result, state_result)
  names(ranked_list)[c(1,2)] <- c("hospital", "state")
  return(ranked_list)
  
}